-- 1. Create table
create table public.promos (
  id bigint generated by default as identity primary key,
  year smallint not null,
  name text,
  key text unique not null
);

-- 2. Enable RLS
alter table public.promos
  enable row level security;

-- 3. Create Policy
CREATE POLICY "policy_name"
ON public.promos
FOR select using 
(auth.role() = 'authenticated');
