-- 1. Create table
create table public.promos (
  id bigint generated by default as identity primary key,
  year smallint not null,
  name text not null
);

-- 2. Enable RLS
alter table public.promos
  enable row level security;

-- 3. Create Policy
create policy "Promos are viewable by everyone."
  on promos for select using (
    true
  );

-- 4. create a promo_key table, to keep these keys privates ...
create table public.promo_key (
  id bigint primary key not null references public.promos(id) on delete cascade,
  key text unique not null
);

-- 5. Enable RLS
alter table public.promo_key
  enable row level security;

-- 6. Create Policy
CREATE POLICY "Promo_key are restricted to authenticated user"
ON public.promo_key
FOR select using 
(auth.role() = 'authenticated');
